### ISSUE TITLE
Option "named" has been removed in JSS v6

### ISSUE THREAD

**Issue by darioghilardi** [thancock20/normalize.jss#1]
Hello,
thanks for your work on this plugin. Unfortunately recently [JSS removed the `named` option](https://github.com/cssinjs/jss/blob/1489bb64f2be2d326bcf7868a15e271de3b0d027/changelog.md#breaking-changes) from JSS v 6.0. I took a quick look at the CLI but I couldn't find any option to generate global styles. Do you have any idea about how we can fix this issue?
I can send a PR but I'm not sure about the correct solution.
Thanks!

**Comment by thancock20** [comment]
It seems they have moved the global option into [its own plugin](https://github.com/cssinjs/jss-global).

Glancing at the readme, it looks like  you need to `npm install --save jss-global` and then change the code from 

```
import Normalize from 'normalize.jss';
import jss from 'jss';

const sheet = jss.createStyleSheet(Normalize, { named: false });
sheet.attach();
```
to

```
import Normalize from 'normalize.jss';
import jss from 'jss';
import global from 'jss-global';

jss.use(global());
const sheet = jss.createStyleSheet('@global': Normalize);
sheet.attach();
```

I'll test this when I have time, but if you get to it first - and it works - then all we'll need to do is update the README.

**Comment by darioghilardi** [comment]
Hey Todd, I tested it tonight and it works exactly as you said. Thank you!
I submitted a PR to update the README so you don't have to spend time on it, if you want me to fix something just tell me.
Thanks a lot for the good work. 👍

**Comment by thancock20** [comment]
Thanks a lot, the PR has been merged.
